### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by p0wn4j** [tpiliposian/Immunefi_bugfixes#1]
In Silo Finance's chapter I'd suggest changing the Base hyperlink to BaseSilo hyperlink.

**Comment by tpiliposian** [comment]
Makes sense, ty.
Fixed in https://github.com/tpiliposian/Immunefi-bugfixes/commit/cb08aac90ee8a9990b3d3fecb7ff96e3f48e87c2
